version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on: 
      - sqlserver
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=sqlserver
      - ASPNETCORE_ENVIRONMENT=Development     
    networks:
      - webapi
  
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus.yaml:etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webapi

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - webapi

networks:
  website:
    driver: bridge

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     SA_PASSWORD: "SqlServer2019!"
  #     ACCEPT_EULA: "Y"
  #     MSSQL_PID: "Developer"
  #   ports:
  #     - "1433:1433"
  # mssqltools:
  #   image: mcr.microsoft.com/mssql-tools
  #   depends_on:
  #     - sqlserver
  #   volumes:
  #     - ./01-BaseCadastro.sql:/tmp/01-BaseCadastro.sql      
  #     - ./init-basecadastro.sh:/tmp/init-basecadastro.sh
  #   command: /bin/bash ./tmp/init-basecadastro.sh


