name: Pipeline - Tech Challenge Fase 02 [.Net 8]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Executando Job de Build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name : Etapa 01 - Checkout do Código Fonte
      uses: actions/checkout@v2

    # - name: Etapa 02 - Configuração Ambiente .NET 8.x
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 8.x

    - name: Etapa 02 - Listando pastas locais
      run: ls

    - name: Etapa 03 - Restaurando Dependências
      run: dotnet restore 

    - name: Etapa 04 - Realizando Build
      run: dotnet build  --no-restore --configuration Release

    - name: Etapa 05 - Executando Testes unitários
      run: dotnet test  --no-build --verbosity normal --configuration Release

    - name: Etapa 06 - Publicando Artefato
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Etapa 07 - Enviar Artefato
      uses: actions/upload-artifact@v2
      with:
        name: published-artifact
        path: ./publish
    
    - name: Etapa 08 - Publicando Container's Docker
      run: docker compose up -d
      
