name: Pipeline - Tech Challenge Fase 02 [.Net 8]
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Executando Job de Build
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
    - name : Etapa 01 - Checkout do Código Fonte
      uses: actions/checkout@v2

    - name: Etapa 02 - Restaurando Dependências
      run: dotnet restore 

    - name: Etapa 03 - Realizando Build
      run: dotnet build  --no-restore --configuration Release

    - name: Etapa 04 - Executando Testes unitários
      run: dotnet test  --no-build --verbosity quiet --configuration Release 2>/dev/null | grep -E 'Test Run Successful|Total tests|Passed|Failed|Skipped'

    - name: Etapa 05 - Publicando Artefato
      run: dotnet publish --no-build --configuration Release --output ./publish

    - name: Etapa 06 - Enviar Artefato
      uses: actions/upload-artifact@v2
      with:
        name: published-artifact
        path: ./publish
    
    - name: Etapa 07 - Publicando Container's Docker
      run: docker compose up -d
      
